### ISSUE TITLE
Type Error: Backbone is undefined

### ISSUE THREAD

**Issue by marcelklehr** [vidigami/backbone-http#6]
The last line seems to be the offending line:
```
/*
	  backbone-http.js 0.7.0
	  Copyright (c) 2013-2014 Vidigami
	  License: MIT (http://www.opensource.org/licenses/mit-license.php)
	  Source: https://github.com/vidigami/backbone-http
	  Dependencies: Backbone.js and Underscore.js.
	 */
	var Backbone, BackboneORM, CAPABILITIES, HTTPCursor, HTTPSync, JSONUtils, Schema, URL, Utils, backboneSync, _, _ref;

	_ref = BackboneORM = __webpack_require__(1), _ = _ref._, Backbone = _ref.Backbone, Utils = _ref.Utils, JSONUtils = _ref.JSONUtils, Schema = _ref.Schema;

	URL = BackboneORM.modules.url;

	backboneSync = Backbone.sync;
```

**Comment by marcelklehr** [comment]
(I'm using component)

**Comment by kmalakoff** [comment]
I tried installing using component and the latest version is 0.7.1. Could it be that you are using an older version?

If that's not it, is the failing line URL = BackboneORM.modules.url because BackboneORM is undefined?

Also, what sort of module solution are you using? (global, webpack, etc)

**Comment by marcelklehr** [comment]
Sorry, I forgot to include the offending line... The last line now is the offending one.

**Comment by marcelklehr** [comment]
I haven't felt the need to use a module solution yet. I publish my packages via component and that's it...

**Comment by kmalakoff** [comment]
OK. Thank you for the information. I see the line now. I'm not sure why this would be happening.

The functionality implemented by that line is trying to reuse Backbone's global sync for HTTP requests. BackboneORM should set a Backbone variable on itself so that the same instance is being used within all BackboneORM modules. This mustn't be being happening.
 
Since you are not using a module system, the hypotheses I can come up with are:

1) Backbone is not being included before BackboneORM. Can you check your dependency loading order is correct...the loading order should be Underscore, Backbone, BackboneORM, BackboneHTTP.

2) The wrong loader path is being followed. I package BackboneORM and BackboneHTTP using webpack's universal loader solution. Can you check to see if it is following CommonJS, AMD, or the global module loading paths for both BackboneORM and BackboneHTTP. Check that when BackboneORM is loaded that Backbone is not undefined; if it is undefined, let me know why related to the loader path.

**Comment by marcelklehr** [comment]
The dependency loading order is correct.
As far as I can see, `BackboneORM.Backbone` is expected to be set in the code above. backbone-orm.js, however sets `BackboneORM.modules.backbone`

**Comment by marcelklehr** [comment]
aha! I'm using an older version of backbone-orm...

**Comment by marcelklehr** [comment]
updated backbone-orm, now I get
```
TypeError: _ is undefined
_.extend(BackboneHTTP, publish);
```

**Comment by kmalakoff** [comment]
Would you be able to trace through using similar instructions as above to see why? It could be loading order or module path. Also, you could try installing via npm and copying the files to ensure you have the latest in case it is another version issue.

Let me know what you find out.

**Comment by marcelklehr** [comment]
Yep, was an issue on my end. I had created a local module backbone-orm, that was overwriting the one I had installed in components. phew. Holy shit...
