### ISSUE TITLE
404 Not Found - Cannot PUT

### ISSUE THREAD

**Issue by marcelklehr** [vidigami/backbone-http#7]
I get 

```
Cannot PUT /locations
```

on the console, when trying to edit an entity (a location in this case).

This seems to be because, backbone-rest expects the update url to look like `PUT /locations/:id`, but backbone-http PUTs to `/locations`.

**Comment by kmalakoff** [comment]
Backbone will call POST when there is no ID and PUT when there is an ID on the model, eg. create vs update.

How Backbone gets the url is through either the urlRoot or url property on the model. I'm assuming that you might be using url instead of [urlRoot](http://backbonejs.org/#Model-urlRoot). Can you please confirm?

**Comment by marcelklehr** [comment]
yea, I'm using url. I fixed this by specifying that it should add the id to the path if there is one.

**Comment by marcelklehr** [comment]
Ah, I get it. I overrode that function by specifying url instead of urlRoot. Thanks :)
